import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--bg-background)",
        surface: "var(--bg-surface)",
        "surface-dim": "var(--bg-surface-dim)",
        "surface-bright": "var(--bg-surface-bright)",
        "surface-container-lowest": "var(--bg-surface-container-lowest)",
        "surface-container-low": "var(--bg-surface-container-low)",
        "surface-container": "var(--bg-surface-container)",
        "surface-container-high": "var(--bg-surface-container-high)",
        "surface-container-highest": "var(--bg-surface-container-highest)",
        "surface-variant": "var(--bg-surface-variant)",
        "on-surface": "var(--text-on-surface)",
        "on-surface-variant": "var(--text-on-surface-variant)",
        primary: "var(--bg-primary)",
        "on-primary": "var(--text-on-primary)",
        "primary-container": "var(--bg-primary-container)",
        "on-primary-container": "var(--text-on-primary-container)",
        "primary-fixed": "var(--bg-primary-fixed)",
        secondary: "var(--bg-secondary)",
        "on-secondary": "var(--text-on-secondary)",
        "secondary-container": "var(--bg-secondary-container)",
        "on-secondary-container": "var(--text-on-secondary-container)",
        tertiary: "var(--bg-tertiary)",
        "on-tertiary": "var(--text-on-tertiary)",
        error: "var(--bg-error)",
        "on-error": "var(--text-on-error)",
        "error-container": "var(--bg-error-container)",
        "on-error-container": "var(--text-on-error-container)",
        outline: "var(--border-outline)",
        "outline-variant": "var(--border-outline-variant)",
        "inverse-surface": "var(--bg-inverse-surface)",
        "inverse-on-surface": "var(--text-inverse-on-surface)",
        "inverse-primary": "var(--bg-inverse-primary)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        display: ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg": ["JetBrains Mono"],
        "headline-md": ["JetBrains Mono"],
        "body-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      spacing: {
        "margin-safe": "40px",
        gutter: "24px",
        "container-max": "1280px",
        "stack-gap": "16px",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "pulse-dot": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.5", transform: "scale(0.8)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        blink: {
          "from, to": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "pulse-cyan": {
          "0%, 100%": { opacity: "0.6", transform: "scale(1)" },
          "50%": { opacity: "1", transform: "scale(1.1)" },
        },
      },
      animation: {
        shimmer: "shimmer 2s linear infinite",
        "pulse-dot": "pulse-dot 1.5s ease-in-out infinite",
        "slide-up": "slide-up 0.3s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
        blink: "blink 1s step-end infinite",
        "pulse-cyan": "pulse-cyan 4s infinite ease-in-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

export default config
