import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#101415",
        surface: "#101415",
        "surface-dim": "#101415",
        "surface-bright": "#363a3b",
        "surface-container-lowest": "#0b0f10",
        "surface-container-low": "#191c1e",
        "surface-container": "#1d2022",
        "surface-container-high": "#272a2c",
        "surface-container-highest": "#323537",
        "surface-variant": "#323537",
        "on-surface": "#e0e3e5",
        "on-surface-variant": "#bcc9cd",
        primary: "#4cd7f6",
        "on-primary": "#003640",
        "primary-container": "#06b6d4",
        "on-primary-container": "#00424f",
        "primary-fixed": "#acedff",
        secondary: "#cebdff",
        "on-secondary": "#381385",
        "secondary-container": "#4f319c",
        "on-secondary-container": "#bea8ff",
        tertiary: "#bcc7de",
        "on-tertiary": "#263143",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        outline: "#869397",
        "outline-variant": "#3d494c",
        "inverse-surface": "#e0e3e5",
        "inverse-on-surface": "#2d3133",
        "inverse-primary": "#00687a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        display: ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg": ["JetBrains Mono"],
        "headline-md": ["JetBrains Mono"],
        "body-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      spacing: {
        "margin-safe": "40px",
        gutter: "24px",
        "container-max": "1280px",
        "stack-gap": "16px",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "pulse-dot": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.5", transform: "scale(0.8)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        blink: {
          "from, to": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "pulse-cyan": {
          "0%, 100%": { opacity: "0.6", transform: "scale(1)" },
          "50%": { opacity: "1", transform: "scale(1.1)" },
        },
      },
      animation: {
        shimmer: "shimmer 2s linear infinite",
        "pulse-dot": "pulse-dot 1.5s ease-in-out infinite",
        "slide-up": "slide-up 0.3s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
        blink: "blink 1s step-end infinite",
        "pulse-cyan": "pulse-cyan 4s infinite ease-in-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

export default config
